version: "3.8"
services:
  web:
    build:
      context: ./btc_trade
    expose:
      - 8000
    ports:
    - 8000:8000
    depends_on:
      - database
    env_file:
      - env_web.dev
      - env_postgres.dev

  database:
    image: postgres:13
    volumes:
      - postgres_storage:/var/lib/postgresql/data/
    env_file:
      - env_postgres.dev

volumes:
  postgres_storage:
