# Generated by Django 3.1.7 on 2021-03-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Paid'), (2, 'Not paid')], default=2)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.userprofile')),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='payments.cryptocurrencyrate')),
            ],
        ),
    ]
