# Generated by Django 3.1.7 on 2021-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Bitcoin'), (2, 'Ethereum')], db_index=True, unique=True)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
